### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by crthpl** [vlang/vos#15]
For this, we need to have a pre-built `x86_64-vos-gcc`, to prevent timing out the CIs (and also make it a lot faster). *One* CI will build `x86_64-vos-gcc`, and then publish it in releases (if the commit has a tag).

List of things we should test:
 - Formatting (`v fmt -verify`)
 - Distro (`make distro`, and then publish `./build/tools/host-gcc/bin/x86_64-vos-gcc` for use by subsequent jobs)
 - Building (`make`)
 - Running (`make run`)

**Comment by youyuanwu** [comment]
I am adding this. Will have PR soon.

**Comment by mintsuki** [comment]
This has been added, I won't use the formatter as it still actively breaks code.

**Comment by youyuanwu** [comment]
I was unable to figure out how to build the gcc (in make distros) separately, and then use artifact to save it and use it in a later stage. The /build folder is very big to save altogether.

The workflow you added works for now. But the majority of the build time is for building gcc.
